# These are supported funding model platforms

# github: [darkfriend]
custom: [
    'https://sobe.ru/na/thankyou_bitrix',
    'https://paypal.me/darkfriend',
    'https://www.tinkoff.ru/cf/36wVfnMf7mo'
]
